version: '3.8'

networks:
    bibbox-default-network:
      external: true

services:

  seeddms-seeddms:
    image: bibbox/seeddms:6.0.11
    container_name:  seeddms-seeddms_tng
    links:
      - seeddms-seeddms-db:seeddms-db
    ports:
      - "80"
    depends_on:
      - seeddms-seeddms-db
    volumes:
      - ./data/var/www/html/seeddms60x/data:/var/www/html/seeddms60x/data:rw
      - ./settings/settings.xml:/var/www/seeddms60x/conf/settings.xml
    networks:
      - bibbox-default-network
      
  seeddms-seeddms-db:
    image: mariadb
    container_name: seeddms-seeddms-db_tng
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=bibbox
      - MYSQL_DATABASE=seeddms
      - MYSQL_USER=seeddms
      - MYSQL_PASSWORD=seeddms4bibbox
    volumes:
      - ./data/var/lib/mysql:/var/lib/mysql:rw
    networks:
      - bibbox-default-network

